# Generated by Django 2.2.12 on 2022-03-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr', models.IntegerField()),
                ('img_url', models.CharField(max_length=2048)),
                ('uni', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=1024)),
                ('date', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=2048)),
            ],
        ),
    ]
